import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./convex-client-provider";
import { ClerkProvider } from "@clerk/nextjs";

// Google fonts configuration for the app
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name
  subsets: ["latin"], // Character set to load
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// SEO metadata for the app (appears in browser tab and search results)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout that wraps all pages in the app
// Provides: Convex connection, fonts, and global styles to entire app
// Used by: Every page automatically (Next.js convention)
export default function RootLayout({
  children, // All page content gets passed here
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {" "}
        {/* Apply font CSS variables */}
        {/* Wraps entire app to provide Convex access to all components */}
        <ClerkProvider>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
